### ISSUE TITLE
Intercommunication between multiple TSERS applications

### ISSUE THREAD

**Issue by tusharmath** [tsers-js/core#20]
I have a fairly large module that I want to break into smaller independent micro-services that can communicate with each other. Each service would have its own `transformations` and `executors` and eventually communicate via `signals`.

I think TSERS would make a lot of sense in this particular case, except that the `TSERS` function returns a `disposable` instead of a stream. I am not sure how it should be designed and what stream should it exactly be returning.

**Comment by milankinen** [comment]
Did my [gitter answer](https://gitter.im/tsers-js/chat?at=5745f751a78d5a256e37c7be) solve this question?

**Comment by tusharmath** [comment]
@milankinen Yes, I think it is a decent approach to solve the problem.
