### ISSUE TITLE
BMI Counter example doesn't work

### ISSUE THREAD

**Issue by ghost** [tsers-js/core#24]
At tsers-js/examples, If you click "BMI Counter" link, you get this error:

```
bundle.js:6258 Uncaught TypeError: g.call is not a function
```

**Comment by milankinen** [comment]
Hmm okay I'll take a look

**Comment by ghost** [comment]
It seems this issue is about the model. More precisely: about the calculated "bmi" property of the model.

**Comment by ghost** [comment]
I think you could close this issue, since it's fixed. 
However it would be useful a more meaningful error message or some kind of check, you know.

**Comment by milankinen** [comment]
The issue is with `ramda` currying which "corrupts" the stacktrace. Unfortunately nothing can be done in TSERS side 😥
